### ISSUE TITLE
CKAN Notification to Admins unclear

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#298]
@acorbi - I got this notification from Hai/davidhill about a dataset that they uploaded: 
![image](https://cloud.githubusercontent.com/assets/14996905/15468095/7f7a147a-20e2-11e6-96b8-69771a953b0b.png)

but when I go to the link it shows her page: 
![image](https://cloud.githubusercontent.com/assets/14996905/15468008/f5886cbc-20e1-11e6-906c-104d7218f0aa.png)

There is no title that's why there is an issue and a number for the record. How do I see this record to check it - there's no indication of how I can view this record.

**Comment by acorbi** [comment]
@prustar that is the screen for the default issue that gets automatically created when an editor creates a dataset (private) on CKAN in order for the admins to review it.

Please read: https://wiki.opendevelopmentmekong.net/partners:content_review In order to publish that dataset you need to delete/close the issue and it will get automatically published.

On th email you have the URL to the dataset, just remove the /issues/3866 part of it

**Comment by acorbi** [comment]
@prustar can we close this issue?
