### ISSUE TITLE
Library Records // How to store data on websites subject to being removed.

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#327]
Please add "SCREENSHOT" as a document type to the library records drop down options. 

All screenshots should be distinguished from other document types and allow for entry of URL and date accessed. @acorbi Please advise whether in the current metadata form it would be appropriate to add these fields or is it possible to allow for a 'if selected' clause when SCREENSHOT is selected to ask for these details? 

I would like to clarify so that when data cleaning commences these records are reassigned.

**Comment by acorbi** [comment]
Hey @prustar, is storing screenshots as library records a normal practice? Images are a very nice format for exposing Open Data. They are not machine readable and so far, I cannot think of a good use case for them. Can you ilustrate one?

I need to understand better what you mean with URL and date accessed? URL of the website/document the screenshot was taken of? Date when the screenshot was done? Is this date different than the created date of the dataset?

In general, there is no problem on adding a new document type, but I would discourage adding data to CKAN deliberatedly. Quality vs Quantity should be the approach.

**Comment by prustar** [comment]
@acorbi -- This has been an outstanding issue for sometime now. One of the problems with freedom of information within the region is that the government will often publish something then remove the data. Almost all of the ELC and mining data was collected from the MAFF and MIME websites, which were subsequently removed due to pressure to be more transparent about these development projects - ironically. 

If I had not taken screenshots of the information at the time and recorded all of the data I could from their sites we would not have the data or maps that are currently present on the ODC site. OD Myanmar is beginning a similar harvesting process with their government websites. Without these documents we can't legitimately prove that the projects exist. 

Random example: https://data.opendevelopmentmekong.net/dataset/companies-invested-in-economic-land-concession-who-registered/resource/7a155356-e6bb-4f11-95b9-eb5934f3dbf7?type=library_record (not a great one). 

Also see wiki on data collection: https://wiki.opendevelopmentmekong.net/public:data_collection
Which outlines the process for attaining screenshots and using the appropriate citation for them. This answers your question regarding URL and date accessed. Note that I also recommend that we use archive.org as well. However this is not consistent and it's more likely that people will take screenshots. 

As it stands there is no consistency within the way these screenshots are referenced in the database making it quite messy and confusing when going to find documentation. 

During the data clean I will require the team to clean out these screenshots and re-allocate them so that they are referenced correctly.

**Comment by acorbi** [comment]
@prustar I have had some thoughts about how to best store this type of resources. Although I understand the importance of archiving that information permanently (which might otherwise be made unavailable at some point by its source ) I would advocate for hosting a copy of the site on archive.org. You will agree with me that the benefits over screenshots are clear:

- an archive of the website allows scraping the data, on the contrary a PDF with an image file does not allow much processing
- contributing to the archive.org makes that information more accessible and contributes to the initiative's goal for a free and open internet
- As already mentioned in the guide, data entry staff can add a link in the corresponding CKAN resource easily

I believe we should adapt the wiki guide and indicate the archive.org solution as the primary one, I would even remove the instructions for taking and uploading screenshots. Do you agree on this?

Regarding the classification of the document type, I have nothing against adding new document types on the CKAN form for library records. However I would suggest "Archived web content" as an alternative name (vs "screenshot") for that new entry on the dropdown box.  This type of records would then normally contain a link to archive.org as a resource.

If you agree with that, I can implement it pretty quickly. please let me know.

**Comment by prustar** [comment]
@acorbi - This doesn't resolve the issue of all of the current screenshots hosted on the datahub and that can't be removed because of their importance as primary references sources and whose links are no longer available to archive. 

I see no problem with using the archive.org site as noted in the Wiki, however it's a habitual act that is not yet occurring amongst the partners or team.  We would need to outline clearly how to use the site on the wiki and ask partners to implement. This is not easy and will take time, having an option in the menu 'Archive web content' will help trigger this habit. Please add it as an option for start. I will edit the wiki. 

If you still object to having a 'screenshot' option then what is the solution to dealing with these existing records? They are all incorrectly sited in the datahub and misleading to users.

**Comment by acorbi** [comment]
> @acorbi - This doesn't resolve the issue of all of the current screenshots hosted on the datahub and that can't be removed because of their importance as primary references sources and whose links are no longer available to archive.

I would add the "Archived web content" document type and use it to mark those Library records already available and containing screenshots.

> We would need to outline clearly how to use the site on the wiki and ask partners to implement#

Definitely, the wiki guide for content upload should be adapted.

>  having an option in the menu 'Archive web content' will help trigger this habit. Please add it as an option for start.

OK, will do.

> If you still object to having a 'screenshot' option then what is the solution to dealing with these existing records? They are all incorrectly sited in the datahub and misleading to users. 

Same as the first answer.

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/ckanext-odm_library/commit/fbd2ef93949387869587ea73c4476a0a6bb51ec9. Now you can select "Archived web content" as part of the values of the **document type** dropdown box
