### ISSUE TITLE
[Feature box] Can we lighten the black tint on the feature box?

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/ckanext-odm_dataset#369]
@acorbi We've discussed this before and you mentioned it's a personal preference. Could we try for a lighter tint? We've received feedback from users who prefer a lighter shades.  

<img width="1439" alt="screen shot 2016-12-15 at 6 56 39 am" src="https://cloud.githubusercontent.com/assets/6489398/21206365/166a7ebc-c294-11e6-9f08-eca04f6754d5.png">

**Comment by prustar** [comment]
@acorbi @gimmemochi @DBishton @Huyeng --- This has now been mentioned since prior to the launch as an issue in visual appeal and usability. There are now at least 3 Github issues raised to either improve the visuals or remove entirely - Along with suggestions. 

I think it's about time it's rectified. We can't continue to specify it as a personal preference when it keeps coming up with users, staff and partners.

**Comment by acorbi** [comment]
@gimmemochi @prustar 

> There are now at least 3 Github issues raised to either improve the visuals or remove entirely

Yeah, let's keep the conversation focused on the existing Issue ->
https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/359 On it, I made a proposal that has @yanoak 's and @DoLinh 's OK (even also @prustar 's seems to agree as long as "those black boxes disappear!")

I agree it is already time to finalize this, however we need first to find consensus among ODM and partners before rolling out the change. @gimmemochi @DBishton @Huyeng can you please provide your thoughts on https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/359, your input is very valuable on there.


I'm closing this one.
