### ISSUE TITLE
CKAN review process 

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#372]
@acorbi -- I just noticed something which might be ok but wanted to raise to check that it's not the case for editors and perhaps should rectify for admins or have a two tired admin role (i.e. Admin and Master Admin?)

When I create a record I can select the record to be public but then when I add a resource it diverts the record to be private. This is expected and what we want because we want to have a second review process by admin staff to ensure standards. See screen shot. 

![image](https://cloud.githubusercontent.com/assets/14996905/21298024/3bfe5aa2-c5de-11e6-9b56-44f16ee33953.png)

When I go back into the record (as ADMIN) I am able to change the privacy setting to public and clear the issue myself. I didn't think this was the expected behaviour, but happy that I can do it so that these aren't held up but not sure that it should be the case for our partners.

PRIVATE:
![image](https://cloud.githubusercontent.com/assets/14996905/21298048/e828b246-c5de-11e6-8011-8e2ea866be28.png)
PUBLIC:
![image](https://cloud.githubusercontent.com/assets/14996905/21298055/0681c5a2-c5df-11e6-8c91-484ad7c75ac1.png)
ISSUE: 
![image](https://cloud.githubusercontent.com/assets/14996905/21298066/307c7e60-c5df-11e6-9603-1aba60b7bf0c.png)

**Comment by acorbi** [comment]
@prustar only admins can select public on the metadata form while creating a new records. As you correctly point out, that record becomes PRIVATE automatically as it is part of the process (an Issue is automatically created) but yeah, you can close that one and make the dataset go PUBLIC.

However, this is only possible for admins, editors can only select PRIVATE on the metadata form ( or even do not see that field since there is only one option for them).

I believe this question is now clarified, closing this Issue. please re-open if you need some more info.
